export const maps = [
  [
    '                                                                         ',
    '                                                                         ',
    '           l        l               l             l       l            l ',
    '                                                                         ',
    '                                                                         ',
    '                                                                         ',
    '                                                                         ',
    '                                                                         ',
    '                                                                         ',
    '                                                                         ',
    '                     =*==%=                                              ',
    '                                                                         ',
    '                                                  $$$$$$$                ',
    'k    $$$$$      k   j      j        j  ^ ^k^ ^ ^ ^$$$$$$$  j        k   -',
    'ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
    'ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
  ],
  [
    '                                                                         ',
    '                                                                         ',
    '                                                                         ',
    '                                                                         ',
    '                                                                         ',
    '                                                                         ',
    '                                                                         ',
    '                                                                         ',
    '                                      $$$                                ',
    '                    ***%***           vvv                                ',
    '                                                                         ',
    '                                !!                       v               ',
    '                                !!                      vvv              ',
    '     $$$$$         @   @        !!                     vvvvv    $$$$$$  -',
    '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                 !!!!!!!!!!!!!!!!!!!!!!',
    '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                 !!!!!!!!!!!!!!!!!!!!!!',
  ],
  [
    '                                                                         ',
    '                                                                         ',
    '                                                                         ',
    '                                                                         ',
    '                                                                         ',
    '                                                                         ',
    '                                                                         ',
    '                                          !!!!                           ',
    '                                ***!              $$$$$                  ',
    '                                                  vvvvv                  ',
    '                                          !!!!    vvvvv    $$$           ',
    '                                %!!!              vvvvv    vvv   $$$     ',
    '     $$$                                          vvvvv          vvv     ',
    '     $$$                 @    @                   vvvvv                 -',
    '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!                !!',
    '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!                !!',
  ],
  [
    '                                                                         ',
    '                                                                         ',
    '                                                                         ',
    '                                                                         ',
    '                        $$$       $$$         $$$         $$$            ',
    '                        vvv       vvv         vvv         vvv            ',
    '                                                                       $$',
    '                   $$$                                                 $$',
    '                   vvv                                                 $$',
    '          %                                                            $$',
    '                $$$                                                    $$',
    '                vvv                                                    $$',
    '  $$$$$                                                                  ',
    '  $$$$$@  @                                                             -',
    '!!!!!!!!!!!!!!!!                                                       !!',
    '!!!!!!!!!!!!!!!!                                                       !!',
  ],
  [
    '                                                                                                                                                ',
    '                                                                                                                                                ',
    '          l        l               l             l       l            l           l        l               l             l       l            l ',
    '                                                                                                                                                ',
    '                                                                                                                                                ',
    '                                                                                                                                                ',
    '                                                                                                                                                ',
    '                                                                                                    $$$                                         ',
    '                                                                                            $$$     ccc     ccc                                 ',
    '                                                                                     $$$    ccc                                                 ',
    '                     ****%*                                                   $$$    ccc                                                        ',
    '                                        c  c                                  ccc                                                               ',
    '                                       cc  cc            c   c         $$$                                                                      ',
    '    k    j        k   j  ^  ^  ^k     ccc  ccc          cc   cc        ccc                                                  j  ^ k     ^  j    -',
    'ccccccccccccccccccccccccccccccccccccccccc  ccccc      cccc   ccccc                                                        cccccccccccccccccccccc',
    'ccccccccccccccccccccccccccccccccccccccccc  ccccc      cccc   ccccc                                                        cccccccccccccccccccccc',
  ],
  [
    '                                                                                                                                         ',
    '                                                                                                                                         ',
    '       l            l           l        l               l             l                    l                      l                     ',
    '                                                                                                                                         ',
    '                                                                                                                                         ',
    '                                                                                                                                         ',
    '                                                                                                                                         ',
    '                                                                                                                                         ',
    '                                                                                                                                         ',
    '           j                                                                      ccc        ccc                                         ',
    '        ***%*******                                                                                                           $$$$$      ',
    '                                      ccc       ccc                    ccc                                                    $$$$$      ',
    '                           ccc                             ccc                                                                $$$$$      ',
    '  j  ^ k       j^                                                                                         k  j  ^ ^ ^ ^k^ ^  j$$$$$k    H',
    'cccccccccccccccccccccc                                                                             cccccccccccccccccccccccccccccccccccccc',
    'cccccccccccccccccccccc                                                                             cccccccccccccccccccccccccccccccccccccc',
  ],
];
